### PR TITLE
Fixed macros patterns

### PR DESCRIPTION
**Pull request by for1997**

### CODE REVIEW

**Comment by radiantmediaplayer** [comment]
Thanks but parentheses are actually not needed here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#using_parentheses

> Parentheses around any part of the regular expression pattern causes that part of the matched substring to be remembered. Once remembered, the substring can be recalled for other use. See Groups and ranges for more details.

**Comment by for1997** [comment]
No, you wrong. Parentheses is needed here. But you can use (?:x) syntax and not remember matched substring. Currently you replace this macros: "[ADCOUNT", "TRANSACTIONID", ..., "LATLONG]", but must  "[ADCOUNT]", "[TRANSACTIONID]", ..., "[LATLONG]"

**Comment by for1997** [comment]
> Thanks but parentheses are actually not needed here:
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#using_parentheses
> 
> > Parentheses around any part of the regular expression pattern causes that part of the matched substring to be remembered. Once remembered, the substring can be recalled for other use. See Groups and ranges for more details.

No, you wrong. Parentheses is needed here. But you can use (?:x) syntax and not remember matched substring. Currently you replace this macros: "[ADCOUNT", "TRANSACTIONID", ..., "LATLONG]", but must "[ADCOUNT]", "[TRANSACTIONID]", ..., "[LATLONG]"

**Comment by radiantmediaplayer** [comment]
Allright my bad. Sorry for the confusion and thanks for insisting. I have added the parentheses in 3.0.5 release.

**Pull request closed without merging**
